# Generated by Django 4.1.4 on 2022-12-31 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Layoff", "Layoff"),
                            ("Hiring", "Hiring"),
                            ("Hiring Frozen", "Hiring Frozen"),
                        ],
                        default="Hiring",
                        max_length=20,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("application_link", models.URLField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
